# Generated by Django 5.2.14 on 2026-09-11 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_alter_projectrevision_revision_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='commessa',
            field=models.CharField(blank=True, help_text='Riferimento commessa/ordine esterno (es. gestionale aziendale). Impostata alla creazione del progetto: tutti i documenti e gli ECN di questo progetto la ereditano automaticamente, non è richiesta di nuovo altrove.', max_length=100, verbose_name='Commessa / ordine'),
        ),
    ]
