# Generated by Django 5.2.14 on 2026-09-14 06:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_project_commessa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectrevision',
            options={'ordering': ['project', '-revision_number'], 'verbose_name': 'Snapshot progetto', 'verbose_name_plural': 'Snapshot progetto'},
        ),
        migrations.RemoveConstraint(
            model_name='projectrevision',
            name='unique_current_snapshot_per_type',
        ),
        migrations.RemoveField(
            model_name='project',
            name='version',
        ),
        migrations.RemoveField(
            model_name='project',
            name='version_scheme',
        ),
        migrations.AlterUniqueTogether(
            name='projectrevision',
            unique_together={('project', 'revision_label'), ('project', 'revision_number')},
        ),
        migrations.AddConstraint(
            model_name='projectrevision',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('project',), name='unique_current_revision_per_project'),
        ),
        migrations.RemoveField(
            model_name='projectrevision',
            name='snapshot_project_version',
        ),
        migrations.RemoveField(
            model_name='projectrevision',
            name='snapshot_project_version_scheme',
        ),
        migrations.RemoveField(
            model_name='projectrevision',
            name='snapshot_type',
        ),
    ]
