# Generated by Django 5.2.14 on 2026-09-16 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditlog', '0002_historical_backfill_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalrecord',
            name='event_type',
            field=models.CharField(choices=[('doc_created', 'Documento creato'), ('doc_draft_created', 'Prima bozza creata'), ('doc_revision_created', 'Nuova revisione creata'), ('doc_submitted', 'Inviato in approvazione'), ('doc_approved', 'Revisione approvata'), ('doc_rejected', 'Revisione rifiutata'), ('doc_published', 'Documento pubblicato'), ('ecn_created', 'ECN creata'), ('ecn_ccb_configured', 'CCB configurata'), ('ecn_dossier_compiled', 'Dossier compilato'), ('ecn_submitted', 'ECN inviata alla CCB'), ('ecn_vote_approved', 'Voto CCB: approvato'), ('ecn_vote_rejected', 'Voto CCB: rifiutato'), ('ecn_approved', 'ECN approvata dalla CCB'), ('ecn_rejected', 'ECN rifiutata dalla CCB'), ('ecn_rejected_pre_ccb', 'ECN rifiutata prima della CCB'), ('ecn_executed', 'ECN eseguita'), ('ecn_closed', 'ECN chiusa'), ('project_created', 'Progetto creato'), ('project_metadata_updated', 'Metadati progetto aggiornati'), ('project_version_saved', 'Versione progetto salvata'), ('project_revision_saved', 'Revisione progetto salvata'), ('project_snapshot_issued', 'Snapshot progetto emesso'), ('generic', 'Evento generico')], max_length=30, verbose_name='Tipo evento'),
        ),
    ]
