# Generated by Django 5.2.14 on 2026-09-21 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auditlog', '0003_alter_historicalrecord_event_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalrecord',
            options={'ordering': ['historical_date', 'recorded_at'], 'permissions': [('can_use_sanatoria', 'Può registrare sanatoria storica')], 'verbose_name': 'Record storico', 'verbose_name_plural': 'Registro storico'},
        ),
    ]
