# Generated by Django 5.2.14 on 2026-09-11 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_document_allow_simple_ecn'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentCodeCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data')),
                ('document_type', models.CharField(max_length=10, verbose_name='Tipo documento')),
                ('last_value', models.PositiveSmallIntegerField(default=0, verbose_name='Ultimo progressivo emesso')),
            ],
            options={
                'verbose_name': 'Contatore codice documento',
                'verbose_name_plural': 'Contatori codice documento',
                'constraints': [models.UniqueConstraint(fields=('date', 'document_type'), name='unique_counter_per_day_and_type')],
            },
        ),
    ]
