# Generated by Django 5.2.14 on 2026-09-14 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0010_documentcodecounter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='category',
            field=models.CharField(choices=[('QUALITY', 'Documento di qualità'), ('PROJECT', 'Documento di progetto')], help_text='Documenti "Altro" (fuori dalla procedura di codifica ufficiale) memorizzano qui direttamente la categoria libera indicata alla creazione.', max_length=50, verbose_name='Categoria'),
        ),
    ]
