# Generated by Django 5.2.14 on 2026-09-14 11:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0011_alter_document_category'),
        ('ecn', '0008_changenotice_locked_at_changenotice_locked_by'),
        ('projects', '0018_alter_projectrevision_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='changenotice',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['draft', 'ccb_preparation', 'under_review', 'approved'])), fields=('document',), name='ecn_single_open_change_notice_per_document', violation_error_message='Esiste già un ECN aperto per questo documento. Deve essere rifiutato o chiuso prima di crearne uno nuovo.'),
        ),
    ]
