# Generated by Django 5.2.14 on 2026-09-16 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecn', '0009_single_open_change_notice_per_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='changenotice',
            name='rejection_stage',
            field=models.CharField(blank=True, choices=[('pre_ccb', 'Prima della CCB'), ('ccb', 'Dalla CCB')], help_text='Valorizzato solo quando status=Rifiutata: distingue un rifiuto del responsabile ECN prima della CCB da un rifiuto votato dalla CCB.', max_length=10, null=True, verbose_name='Fase del rifiuto'),
        ),
    ]
