# Generated by Django 5.2.14 on 2026-09-16 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecn', '0010_changenotice_rejection_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changenotice',
            name='status',
            field=models.CharField(choices=[('draft', 'Bozza'), ('ccb_preparation', 'Istruttoria CCB'), ('under_review', 'In Valutazione CCB'), ('approved', 'Approvato'), ('rejected', 'Rifiutato'), ('closed', 'Chiuso')], default='draft', max_length=20, verbose_name='Stato'),
        ),
    ]
